services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    env_file:
      - secrets.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  django:
    image: samirelanduk/samireland_django
    env_file:
      - secrets.env
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - 8000:80
    depends_on:
      - db
  nginx:
    image: samirelanduk/samireland_nginx
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - django
    ports:
      -  7000:80
volumes:
  static_volume:
  media_volume:
  postgres_data: