version: '3.7'

# Only used to build

services:
  django:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    image: samirelanduk/samireland_django
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: samirelanduk/samireland_nginx