# Generated by Django 4.2.2 on 2024-10-15 20:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='text',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['bold', 'link', 'italic', 'h2', 'h3', 'ol', 'ul', 'code', 'strikethrough'])), ('figure', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.RichTextBlock(features=['bold', 'link', 'italic'], required=False))], icon='image')), ('code', wagtail.blocks.StructBlock([('language', wagtail.blocks.CharBlock()), ('code', wagtail.blocks.TextBlock())], icon='code'))], use_json_field=True),
        ),
    ]
